// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_B_bix6V4d5JjSdGPI4YkrUsppZfwxk',
    appId: '1:629458881090:web:e7d328e6d7de31ca783bdb',
    messagingSenderId: '629458881090',
    projectId: 'sc2leaderboards',
    authDomain: 'sc2leaderboards.firebaseapp.com',
    storageBucket: 'sc2leaderboards.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdoE197CK0FuISR1pxtv8m34ihtQZHz_8',
    appId: '1:629458881090:android:9c09fb6f5dfd0932783bdb',
    messagingSenderId: '629458881090',
    projectId: 'sc2leaderboards',
    storageBucket: 'sc2leaderboards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGL5amKqnsDAgiVhTW8h06CxEGmQIxYM4',
    appId: '1:629458881090:ios:675a748cb1673760783bdb',
    messagingSenderId: '629458881090',
    projectId: 'sc2leaderboards',
    storageBucket: 'sc2leaderboards.appspot.com',
    iosBundleId: 'app.hobogames.sc2Leaderboards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGL5amKqnsDAgiVhTW8h06CxEGmQIxYM4',
    appId: '1:629458881090:ios:abdeffa443d17995783bdb',
    messagingSenderId: '629458881090',
    projectId: 'sc2leaderboards',
    storageBucket: 'sc2leaderboards.appspot.com',
    iosBundleId: 'app.hobogames.sc2Leaderboards.RunnerTests',
  );
}
